// Generates the world map's geometry at build time, from Natural Earth 110m
// (world-atlas 2.0.2). Nothing here runs in the browser and `npm run build`
// never needs it: the output is committed to src/data/.
//
//   land-dots.json          two dot grids in an equirectangular projection,
//                           cropped to 84N..58S: `wide` (2.5 degree spacing,
//                           1440 x 568) and `narrow` (5 degree, 360 x 142), each
//                           a single SVG path of zero-length subpaths that render
//                           as square dots.
//   country-centroids.json  the centroid and area of each country's largest
//                           polygon, keyed by Natural Earth name, so a marker
//                           sits on the mainland rather than being pulled toward
//                           Alaska or an island chain.
import { readFile, writeFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import { feature } from 'topojson-client';

const require = createRequire(import.meta.url);
const land110 = JSON.parse(await readFile(require.resolve('world-atlas/land-110m.json'), 'utf8'));
const countries110 = JSON.parse(await readFile(require.resolve('world-atlas/countries-110m.json'), 'utf8'));

const NORTH = 84;
const SOUTH = -58;

const polygonsOf = (geom) =>
  geom.type === 'Polygon' ? [geom.coordinates] : geom.type === 'MultiPolygon' ? geom.coordinates : [];

// Ray casting on one ring, in lon/lat.
function inRing(lon, lat, ring) {
  let inside = false;
  for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
    const [xi, yi] = ring[i];
    const [xj, yj] = ring[j];
    if (yi > lat !== yj > lat && lon < ((xj - xi) * (lat - yi)) / (yj - yi) + xi) inside = !inside;
  }
  return inside;
}

const bbox = (ring) => {
  let w = Infinity, e = -Infinity, s = Infinity, n = -Infinity;
  for (const [x, y] of ring) { w = Math.min(w, x); e = Math.max(e, x); s = Math.min(s, y); n = Math.max(n, y); }
  return { w, e, s, n };
};

const landPolys = feature(land110, land110.objects.land).features.flatMap((f) => polygonsOf(f.geometry));
const indexed = landPolys.map((rings) => ({ rings, box: bbox(rings[0]) }));

function onLand(lon, lat) {
  for (const { rings, box } of indexed) {
    if (lon < box.w || lon > box.e || lat < box.s || lat > box.n) continue;
    if (!inRing(lon, lat, rings[0])) continue;
    if (rings.slice(1).some((hole) => inRing(lon, lat, hole))) continue;
    return true;
  }
  return false;
}

function grid(step, k) {
  const parts = [];
  let dots = 0;
  const round = (v) => Math.round(v * 10) / 10;
  for (let lat = NORTH - step / 2; lat > SOUTH; lat -= step) {
    for (let lon = -180 + step / 2; lon < 180; lon += step) {
      if (!onLand(lon, lat)) continue;
      parts.push(`M${round((lon + 180) * k)} ${round((NORTH - lat) * k)}h0`);
      dots++;
    }
  }
  return { k, step, width: 360 * k, height: (NORTH - SOUTH) * k, dots, d: parts.join('') };
}

const wide = grid(2.5, 4);
const narrow = grid(5, 1);

await writeFile(
  new URL('../src/data/land-dots.json', import.meta.url),
  JSON.stringify(
    {
      _about: 'Generated by scripts/make-geo.mjs from Natural Earth 110m (world-atlas 2.0.2). Do not edit by hand.',
      north: NORTH,
      south: SOUTH,
      wide,
      narrow,
    },
    null,
    2
  ) + '\n'
);

// Planar area and centroid of a ring, in lon/lat. Adequate for placing a marker.
function ringCentroid(ring) {
  let a = 0, cx = 0, cy = 0;
  for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
    const [x0, y0] = ring[j];
    const [x1, y1] = ring[i];
    const f = x0 * y1 - x1 * y0;
    a += f; cx += (x0 + x1) * f; cy += (y0 + y1) * f;
  }
  a /= 2;
  return { area: Math.abs(a), lon: cx / (6 * a), lat: cy / (6 * a) };
}

const centroids = {};
for (const f of feature(countries110, countries110.objects.countries).features) {
  const polys = polygonsOf(f.geometry);
  if (!polys.length || !f.properties?.name) continue;
  const largest = polys.map((p) => ringCentroid(p[0])).sort((a, b) => b.area - a.area)[0];
  centroids[f.properties.name] = {
    lon: Math.round(largest.lon * 100) / 100,
    lat: Math.round(largest.lat * 100) / 100,
    area: Math.round(largest.area * 100) / 100,
  };
}

await writeFile(
  new URL('../src/data/country-centroids.json', import.meta.url),
  JSON.stringify({ _about: 'Generated by scripts/make-geo.mjs. Largest-polygon centroid per country, Natural Earth names.', ...centroids }, null, 2) + '\n'
);

console.log(`land-dots.json: wide ${wide.dots} dots (${(wide.d.length / 1024).toFixed(1)} KB), narrow ${narrow.dots} dots (${(narrow.d.length / 1024).toFixed(1)} KB)`);
console.log(`country-centroids.json: ${Object.keys(centroids).length} countries`);
